### ISSUE TITLE
搜索界面的图源选择框能否增加一个反选按钮?

### ISSUE THREAD

**Issue by YellowOrangeHuang** [Haleydu/Cimoc#10]
图源框是默认全选的，当想搜索单个图源时，需要一个一个勾取消，所以能否增加一个反选按钮，方便搜索单个源，感谢。
![photo_2020-07-19_16-21-16](https://user-images.githubusercontent.com/46016407/87870662-da427d00-c9dc-11ea-8550-431cc2b29c35.jpg)

**Comment by Haleydu** [comment]
好的，争取下个版本更新功能。
