### ISSUE TITLE
[CS]动漫屋漫画解析错误或者无法打开。

### ISSUE THREAD

**Issue by ffffscp** [Haleydu/Cimoc#100]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [x] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by YellowOrangeHuang** [comment]
老兄你最好提供下漫画名确认下该漫画在源网站是不是能正常观看。
漫画屋的漫画大概分三种，
一是像星海游侠这种，可以直接阅读的；
二是像粗点心战争这种，在国内网是能搜到，但需要挂代理，才可以搜索出来并阅读；
三是像伊甸园这种限制级，不但国内网搜不到，而且进入详情页会有提示弹窗的，这种最多开个代理搜出来，没办法直接通过Cimoc阅读。

**Comment by YellowOrangeHuang** [comment]
我这边用漫画屋，第一类和第二类漫画，在适合的情况下是能正常阅读的

**Comment by ffffscp** [comment]
我看的是武侠港漫，大唐双龙传，神雕侠侣这些都是可以直接看的，现在看不了了，按你说的现在可能需要挂梯子了。

**Comment by YellowOrangeHuang** [comment]
@ffffscp  这俩现在就能直接观看啊？莫不是版本不是最新版，或者换一个好的网络再试试。

如果在cimoc加载漫画章节时，网络出了问题，应用是会立刻解析失败的。
![Screenshot_2020-09-01-16-32-25-715_com haleydu cimoc](https://user-images.githubusercontent.com/46016407/91826995-deff7f80-ec70-11ea-8856-6c3ec3809a9b.jpg)

**Comment by ffffscp** [comment]
哦，我看的是黄玉郎版的，我试了一下用梯子就可以正常观看了，多谢你的建议。
