### ISSUE TITLE
升到1.6.15检查更新失败

### ISSUE THREAD

**Issue by KeyTeams** [Haleydu/Cimoc#104]
升到1.6.15后检查更新失败，备份后清除数据也没用

**Comment by Haleydu** [comment]
具体是怎么失败?从哪个版本升级到1.6.5检测更新失败，1.6.5就是最新的

**Comment by BiggestDM** [comment]
> 具体是怎么失败？从哪个版本升级到1.6.5检测更新失败，1.6.5就是最新的

应该是漫画章节更新失败
![Screenshot_2020-09-04-08-52-23-523_com haleydu cimoc](https://user-images.githubusercontent.com/46108146/92187363-1c8c2480-ee8c-11ea-89b5-7d89d637d30d.jpg)

**Comment by KeyTeams** [comment]
> 具体是怎么失败?从哪个版本升级到1.6.5检测更新失败，1.6.5就是最新的

点击在收藏页右下角的检查更新，然后手机状态栏会显示检查进度，但是一会儿后就会提示 检查更新失败。我是从1.6.14升到1.6.15的

**Comment by ParanoiaIsGreat** [comment]
我也同上

**Comment by Haleydu** [comment]
下载1.6.16-beta01版本试试看，我手机没办法复现，所以修复较慢。需要一些信息：更新失败的，收藏的漫画是哪个漫画源的漫画较多？或者收藏了哪些漫画源的漫画？

**Comment by KeyTeams** [comment]
> 下载1.6.16-beta01版本试试看，我手机没办法复现，所以修复较慢。需要一些信息：更新失败的，收藏的漫画是哪个漫画源的漫画较多？或者收藏了哪些漫画源的漫画？

试了好久，发现我这边删除 {汗汗酷漫} 这个漫画源的漫画后检查更新就正常了。这个漫画源是很久以前收藏的，现在用得最多的漫画源是动漫堆、动漫之家V2、动漫屋。

**Comment by Haleydu** [comment]
好的，感谢，那我知道原因了，汗汗酷漫url报毒，本地的url被我删了。汗汗酷漫url又被我放到后端去获取了。我把后端链接打开应该就正常了

**Comment by Edanwon** [comment]
> 好的，感谢，那我知道原因了，汗汗酷漫url报毒，本地的url被我删了。汗汗酷漫url又被我放到后端去获取了。我把后端链接打开应该就正常了

辛苦了，不过请问后端服务器是否是境外服务器？我今晚获取更新时仍然提示失败(国内电信)，挂上梯子(俄罗斯)以后也是卡在更新失败的那个点上，不失败但也不会继续往后面检查更新。
移除了汗汗酷漫以后正常了，不知道未来更新是否可以加入超时则跳过的功能
