### ISSUE TITLE
关于Haleydu版与feilongfl版下载漫画事宜

### ISSUE THREAD

**Issue by Zfeng-zhuang** [Haleydu/Cimoc#105]
想了解在Haleydu版扫描到feilongfl版的漫画后，
是否即使卸载feilongfld版的app，已下载的漫画还能正常在Haleydu中查看，并不会因为卸载了feilongfl版的app导致已下载漫画丢失。
望解答。

**Comment by Haleydu** [comment]
下载的漫画还是在的，到本地导入就行了。而且两个版本是可以共存的。不需要卸载feilong的版本。

**Comment by Zfeng-zhuang** [comment]
> 下载的漫画还是在的，到本地导入就行了。而且两个版本是可以共存的。不需要卸载feilong的版本。

**Comment by Zfeng-zhuang** [comment]
目前就是两个版本共用，但为了统一，希望只是保留haleydu版，但之前在feilongfl下载了大量漫画，不想丢失。
反正只要我在haleydu版扫描好了漫画，即使把feilongfl版卸载了还是可以查看到的是吧。

**Comment by Haleydu** [comment]
可以看到
