### ISSUE TITLE
拖动进度条闪退问题。

### ISSUE THREAD

**Issue by KotlinLan** [Haleydu/Cimoc#107]
![image](https://user-images.githubusercontent.com/50512101/92891756-c64e5100-f44a-11ea-8a42-21c0f261d781.png)

**Comment by Haleydu** [comment]
好的，会尽快修复

**Comment by Haleydu** [comment]
需要一些信息以便更好修复，阅读哪个源的漫画造成的

**Comment by KotlinLan** [comment]
![image](https://user-images.githubusercontent.com/50512101/92921689-1c30f200-f467-11ea-898d-57dc7710033a.png)
这个漫画源，随便哪个章节都会。

**Comment by Haleydu** [comment]
好的，新版本已修复
