### ISSUE TITLE
希望可以实现独立设置翻页模式

### ISSUE THREAD

**Issue by hanxin1997** [Haleydu/Cimoc#11]
很多漫画有卷轴和翻页的 每次都需要切换很麻烦， 希望可以独立设置，每个漫画独立的设置 参考meow或tachiyomi。
可以参考https://github.com/mabDc/Meow 这个也是一个很优秀的漫画软件 可惜被废弃了。
感谢。

**Comment by Haleydu** [comment]
感谢你的建议。请再细心熟悉一下本软件，这个功能软件已经实现了。
参考如下：
设置>阅读配置>自定义长按（点击）事件>切换阅读模式。

**Comment by hanxin1997** [comment]
> 请再细心熟悉一下本软件，这个功能软件已经实现了。
> 参考如下：
> 设置>阅读配置>自定义长按（单击）事件>切换阅读模式。

指的是类似meow或tachiyomi的 有一个全局设置和漫画的个人设置，这个功能还是要切换一下，当然现在这个功能也很方便，另外一提oh和漫画堆好像不能看。
