### ISSUE TITLE
[CS]漫画源请求

### ISSUE THREAD

**Issue by hanxin1997** [Haleydu/Cimoc#13]
希望可以添加app源，兔漫
那个更新tx漫画很快。
另外希望可以建立tg群组方便交流。

**Comment by Haleydu** [comment]
留个兔漫的网站，我分析一下是否添加到图源

**Comment by hanxin1997** [comment]
> 留个兔漫的网站，我分析一下是否添加到图源

app源 没有网页版 app地址：https://www.lanzous.com/b0e7g182j

**Comment by Haleydu** [comment]
这个apk兔漫自己的服务器，没有公开网页版，我还是不要去破解这个apk了。一切以网络上能搜索到的资源为主。
