### ISSUE TITLE
[CS]动漫屋部分漫画无法解析

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#131]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫屋

## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [x] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [x] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 
V1.6.19

具体漫画：
http://m.dm5.com/manhua-mengyintongxuetaiguorenzhendejiaowangfangshi
http://www.dm5.com/manhua-mengyintongxuetaiguorenzhendejiaowangfangshi
http://www.dm5.com/manhua-zaiyishijiemigongkaihougong
漫画需要国外ip，已使用相关工具，在网页浏览器上正常打开，在cimoc中提示解析失败。

~~同样的限制漫画 http://www.dm5.com/manhua-huayuanjiadeshuangzi 可以在cimoc中正常打开阅读。~~ 也出现上述问题

已排除代理问题，查看代理日志已将相关域名代理。

**Comment by zhongfly** [comment]
我猜测是没对m.dm5这个域名的动漫屋做适配？

**Comment by YellowOrange98** [comment]
不是，你尝试下挂代理访问，有的漫画是要用代理才能解析的

**Comment by zhongfly** [comment]
> 不是，你尝试下挂代理访问，有的漫画是要用代理才能解析的

你认真看过我做的分析了吗？使用了代理，在网页版可以看，并且同样的限制漫画也是可以看的。
而且我还用代理app的日志功能确定了的确是走了代理
![Screenshot_20201108204535](https://user-images.githubusercontent.com/11155705/98465341-7221dc00-2203-11eb-90e7-4a73dc87c679.png)

能不能看过了再说？
除非你证明你挂了代理，在cimoc上能正常看我举例的这一部漫画，才能反证是我代理失败导致的。

**Comment by YellowOrangeHuang** [comment]
没看到说明，抱歉。

**Comment by zhongfly** [comment]
@Haleydu 希望能处理一下
我抓包发现了原因，链接结尾带不带/的问题，以及软件对响应301的处理
http://www.dm5.com/manhua-mengyintongxuetaiguorenzhendejiaowangfangshi 会返回301，跳转到结尾加/的地址
请求 http://www.dm5.com/manhua-mengyintongxuetaiguorenzhendejiaowangfangshi/ 则一切正常
![photo_2020-12-28_16-40-29](https://user-images.githubusercontent.com/11155705/103201699-7d53d700-492b-11eb-8e45-c6179146b1e8.jpg)


另外这个源的章节顺序是错误的，望修复

**Comment by Haleydu** [comment]
新版本已修复
