### ISSUE TITLE
[CS]漫画堆解析错误

### ISSUE THREAD

**Issue by 2436819833** [Haleydu/Cimoc#139]
用的1.6.21，收藏了很多漫画，大多数全是漫画堆的，今天收藏了几部后，漫画堆源的漫画开始全部解析错误，其他源正常，已试过卸载重装恢复备份，依旧无解，是因为漫画堆源收藏的漫画太多了吗。可以qq提供备份文件查找原因

**Comment by 2436819833** [comment]
减少部分收藏后，能解决这种情况，挺玄乎的

**Comment by 2436819833** [comment]
好吧，漫画堆网站炸了

**Comment by samuel-12138** [comment]
漫画堆更换了域名，改成了manhuadai.com，替换域名即可，另外他们网站还出现了ssl证书错误，忽略即可

**Comment by dsb2333** [comment]
怎么替换？

**Comment by Haleydu** [comment]
已修复
