### ISSUE TITLE
[CS]漫画源问题

### ISSUE THREAD

**Issue by 1411907612** [Haleydu/Cimoc#141]
漫画堆的漫画源出现问题
应该是漫画堆的网址从manhuabei改成了manhuadai

**Comment by 2436819833** [comment]
网址全名是什么，manhuadai.com进不去啊

**Comment by 1411907612** [comment]
https://m.manhuadai.com/

**Comment by hellowolrds** [comment]
https://wws.lanzous.com/b01tpu2dg， 里面是经过我优化的app，源更换很多。

**Comment by hellowolrds** [comment]
这个开源项目，感觉唯一的缺点就是不能动态导入源，如果和异次元那样就好了，源可以动态导入编辑

**Comment by Haleydu** [comment]
已修复
