### ISSUE TITLE
1.6.23自动切割大图功能出现问题

### ISSUE THREAD

**Issue by CLSA95** [Haleydu/Cimoc#148]
切割后只占半屏
![Screenshot_20201203-122014](https://user-images.githubusercontent.com/75407996/100963698-eaa95d80-3561-11eb-9adf-5d1d9bef3605.jpg)

**Comment by CLSA95** [comment]
标签加错了不好意思……好像编辑不了标签？

**Comment by Haleydu** [comment]
漫画名叫什么？我马上修复一下。我最近没有看大图片的漫画，没留意这个问题。

**Comment by ahxbwjsh** [comment]
> 漫画名叫什么？我马上修复一下。我最近没有看大图片的漫画，没留意这个问题。

全职猎人 咒术回战 基本上所有大图都只有一半
