### ISSUE TITLE
[CS]漫画堆漫画无法观看，也不逼出来

### ISSUE THREAD

**Issue by ffffscp** [Haleydu/Cimoc#159]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
漫画堆
## 在以下环节中出现错误
- [ ！] 搜索
- [ ] 章节信息
- [！ ] 图片加载

## 你是否使用科学上网工具
- [！ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: v. 1.6.24

**Comment by samuel-12138** [comment]
源网站打不开，这是真的gg了吧 (눈_눈)

**Comment by chentgp** [comment]
> 源网站打不开，这是真的gg了吧 (눈_눈)

可以在苹果手机的Yealico打开新漫画堆

**Comment by chentgp** [comment]
Yealico

**Comment by Haleydu** [comment]
漫画堆现在的网站地址知道吗？

**Comment by chentgp** [comment]
yealico小小站好像有二维码

**Comment by chentgp** [comment]
这yealico的小小站分享二维码，只有苹果手机用户才能确定这里的分享有没有挂掉？https://yealicositemarket.home.blog/%e7%ab%99%e7%82%b9%e8%a7%84%e5%88%99%e5%88%97%e8%a1%a8/

**Comment by BA7LCY** [comment]
漫画堆改成漫画袋了

**Comment by Haleydu** [comment]
> 漫画堆改成漫画袋了

有网址吗？

**Comment by BA7LCY** [comment]
> > 漫画堆改成漫画袋了
> 
> 有网址吗？

manhuadai  不过也打不开了

**Comment by Haleydu** [comment]
![image](https://user-images.githubusercontent.com/44172947/102992682-9f79dd80-4556-11eb-9e3e-05d8313c0c70.png)

刚刚查了一下，漫画堆所有域名都用不了，等哪天漫画恢复了，再修复漫画堆。

**Comment by darriousliu** [comment]
> ![image](https://user-images.githubusercontent.com/44172947/102992682-9f79dd80-4556-11eb-9e3e-05d8313c0c70.png)
> 
> 刚刚查了一下，漫画堆所有域名都用不了，等哪天漫画恢复了，再修复漫画堆。

改名了现在manhuadai.com重定向到爱优漫了[iyouman.com](url)

**Comment by darriousliu** [comment]
这个iyouman的漫画抓不到搜索的API
我猜测是用这个API获取到所有漫画的信息，然后做本地搜索
![image](https://user-images.githubusercontent.com/60057825/103154585-49fe3480-47d3-11eb-9dd2-b3691dd5dd0a.png)
![`RTGK%DN)SBRN BN{5CH)5X](https://user-images.githubusercontent.com/60057825/103154593-51bdd900-47d3-11eb-9ce3-7c6a0df9b2a2.png)
好像只有2759部漫画，感觉挺少的，看情况添加这个漫画源吧

**Comment by Haleydu** [comment]
漫画堆已消失
