### ISSUE TITLE
[CS]作者大大是弃坑了吗，这么久没维护了，没弃坑的话希望能半个月左右瞅一下这个意见反馈

### ISSUE THREAD

**Issue by hanfeng8** [Haleydu/Cimoc#160]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by Haleydu** [comment]
一直在关注，大部分漫画都可以看，就没有去修复了。而且最近很多漫画网站挂了。会慢慢修复。

**Comment by Schwi-ExMachina** [comment]
> 一直在关注，大部分漫画都可以看，就没有去修复了。而且最近很多漫画网站挂了。会慢慢修复。

可以的话希望提供一个高级模式可以自己修复 
最好甚至可以提供列表批量地址替换功能
例如搜记录里的manhuadui替换manhuabei之类的
漫画堆经常隔三差五就改一点点

**Comment by Haleydu** [comment]
条件允许的话，准备弄个软件后端自动修复的功能。目前精力有限，慢慢来
