### ISSUE TITLE
[CS]大佬請加一个漫畫源

### ISSUE THREAD

**Issue by g573** [Haleydu/Cimoc#162]
#這个不錯真全，看漫画（原本不是这名字） https://m.manhuagui.com/

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by g573** [comment]
哦这个还要挂梯子才行

**Comment by Zfeng-zhuang** [comment]
这不就是漫画柜吗，这漫画源已经有了。

**Comment by g573** [comment]
> 这不就是漫画柜吗，这漫画源已经有了。

呃，为啥我在网页上是看漫画，改名了？

**Comment by Zfeng-zhuang** [comment]
> > 这不就是漫画柜吗，这漫画源已经有了。
> 
> 呃，为啥我在网页上是看漫画，改名了？

域名不写着漫画柜吗

**Comment by g573** [comment]
😅有就不说了，域名的话我这看是看漫画，不知道咋回事



---原始邮件---
发件人: "Zfeng-zhuang"<notifications@github.com&gt;
发送时间: 2020年12月27日(周日) 晚上6:40
收件人: "Haleydu/Cimoc"<Cimoc@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"g573"<450084951@qq.com&gt;;
主题: Re: [Haleydu/Cimoc] [CS]大佬請加一个漫畫源 (#162)




   
这不就是漫画柜吗，这漫画源已经有了。
  
呃，为啥我在网页上是看漫画，改名了？
  
域名不写着漫画柜吗
