### ISSUE TITLE
当系统开启深色模式导致部分图片变成反色

### ISSUE THREAD

**Issue by nd002723** [Haleydu/Cimoc#164]
![Screenshot_2020-12-30-22-14-25-329_com.haleydu.cimoc.jpg](https://user-images.githubusercontent.com/27563570/103356689-6b6d6200-4aec-11eb-8a1c-d0a3474939f4.jpg)
系统版本:MIUI12.0.1
软件版本:1.6.24

**Comment by zhongfly** [comment]
提问前请自行搜索是否重复
https://github.com/Haleydu/Cimoc/issues/18
