### ISSUE TITLE
奇漫屋的漫画资源搜索不到，麻烦大神看看是什么问题？

### ISSUE THREAD

**Issue by luffyhaha** [Haleydu/Cimoc#172]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by Haleydu** [comment]
没问题啊

**Comment by luffyhaha** [comment]
但是为什么加载奇漫屋的漫画老是不能直接看到下一个最新的话




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午4:40
收件人: "Haleydu/Cimoc"<Cimoc@noreply.github.com&gt;; 
抄送: "Scorpius"<2367792532@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Haleydu/Cimoc] 奇漫屋的漫画资源搜索不到，麻烦大神看看是什么问题？ (#172)





 
没问题啊

**Comment by Haleydu** [comment]
新版本已修复
