### ISSUE TITLE
可以修复一下oh漫画 漫画堆  漫画柜嘛

### ISSUE THREAD

**Issue by a72714836** [Haleydu/Cimoc#175]
这三个都是比较不错的漫画源

**Comment by Haleydu** [comment]
oh已经修复了，漫画堆官网挂了无法修复，漫画柜也没问题啊。下载最新版本试试吧。1.6.27

**Comment by a72714836** [comment]
> oh已经修复了，漫画堆官网挂了无法修复，漫画柜也没问题啊。下载最新版本试试吧。1.6.27

谢谢咯
