### ISSUE TITLE
主题及颜色问题

### ISSUE THREAD

**Issue by qqlkj12** [Haleydu/Cimoc#18]
手机k20pro，系统miui12
软件版本1.5.6(590)
深色模式下会偶发出现漫画反色的现象
主题背景颜色也希望别跟随系统了

**Comment by zhongfly** [comment]
https://github.com/Kr328/ClashForAndroid/issues/558
小米自己的问题

**Comment by Haleydu** [comment]
小米手机的bug，无法解决
