### ISSUE TITLE
请问如何根据 AES 加密字符串获取对应的 Key 或 iv 呀？

### ISSUE THREAD

**Issue by jijiucheng** [Haleydu/Cimoc#182]
有时候获取到一个 AES 加密字符串，但是不知道如何获取对应的 Key 或 iv ，所以就没法做到相应的解密，获取不到实际的字符串。请问一下，这个该如何获取呀？

**Comment by Haleydu** [comment]
网页js代码上一般都会有对应的key和iv，想办法找到key和iv就行了，key和iv可能会加密，加密的就需要自己去解密。通过AES加密后的字符串是没办法获取key和iv。

**Comment by jijiucheng** [comment]
> 网页js代码上一般都会有对应的key和iv，想办法找到key和iv就行了，key和iv可能会加密，加密的就需要自己去解密。通过AES加密后的字符串是没办法获取key和iv。

关键好多时候这个 key 和 iv 都是进行了二次加密，想找到有点麻烦！
还有一种情况，我看到有的加密字符串，带有加盐的情况，常规的这种加盐，有好的处理方式吗？

**Comment by jijiucheng** [comment]
对了，漫画堆、漫画呗，现在更改域名为 [m.ykmh.com](m.ykmh.com) 了，也更名为 “优酷漫画” 了，方便再次加一下吗？

**Comment by darriousliu** [comment]
这不开发iOS的人么😄😄

**Comment by jijiucheng** [comment]
> 这不开发iOS的人么😄😄

？？？
