### ISSUE TITLE
一个阅读动漫之家隐藏漫画的api

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#187]
通过搜索，我们可以得到一个漫画的comic_id。如果是隐藏漫画，向v3api或是v2api都会直接返回漫画不存在，无法获得漫画详情。
如果向该api请求漫画信息(请求地址 http://api.dmzj.com/dynamic/comicinfo/<comic_id>.json )，则会返回漫画的详情，得到每个章节的id。
之后向 https://m.dmzj.com/chapinfo/<comic_id>/<章节id>.html 请求漫画图片地址，返回的图片地址域名为dmzj.com无法访问，但改成dmzj1.com后可以打开图片。

以隐藏漫画绝望hiroin为例，comic_id为50654，请求 http://api.dmzj.com/dynamic/comicinfo/50654.json 获得漫画章节信息，最新章节id为108495，请求 https://m.dmzj.com/chapinfo/50654/108495.html 得到图片地址。 第一张图片为 https://images.dmzj.com/j/%E7%BB%9D%E6%9C%9Bhiroin/%E7%AC%AC67%E8%AF%9D/1.jpg 无法访问，改为dmzj1.com域名后 https://images.dmzj1.com/j/%E7%BB%9D%E6%9C%9Bhiroin/%E7%AC%AC67%E8%AF%9D/1.jpg 可以访问。

**Comment by zhongfly** [comment]
@lx200916 我觉得可以考虑优先用v3的api，当api返回漫画不存在时再调用上述的api

**Comment by TkzcM** [comment]
也可以直接拼出每话的 zip 地址
https://imgzip.dmzj1.com/ **first_letter** / **comic_id** / **chapter_id** .zip
