### ISSUE TITLE
[CS]能否优化UI界面

### ISSUE THREAD

**Issue by KoedaNagi** [Haleydu/Cimoc#19]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/2)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
V1.4.8.8xxx
下载界面有些不理想和本地栏完全无用。请设计设计

**Comment by Haleydu** [comment]
感谢你的介意，我自己也有考虑过这个问题，后期如果时间充足会考虑更新。目前阶段不太可能大改UI，我只是个独立开发者，改UI难度不大但是工作量太大了，需要重新设计界面布局，我对自己的设计天赋不敢苟同，而且时间精力有限，暂时只会去解解BUG，增加一些小需求，更新失效的漫源或者添加一些不错的新漫源。

我的更新方向是：

1. 能正常看大部分漫画
2. 界面简洁为主
3. 拒绝广告
4. 解决apk影响体验的问题

项目开源就是希望大家一起开发，欢迎大家pull requests。
