### ISSUE TITLE
关于cimoc

### ISSUE THREAD

**Issue by sssmy999** [Haleydu/Cimoc#199]
oppo手机下载的cimoc app 总会提示有病毒风险

**Comment by Haleydu** [comment]
代码是开源的，github上有老哥抓包过本软件，软件有问题早被喷了。而且github上大佬也多，真的有毒软件早死了。我也尝试过，去修复（某腾）误报毒的代码无法解决。报毒问题目前我不会解啊，估计是大厂垄断打压吧。

apk由travis自动编译打包的，编译的Travis记录可以看到打印的md5，release上也有输出md5信息，软件md5跟提供的md5信息对上就行了。

**Comment by master-lzh** [comment]
确实，怕有毒可以不用

**Comment by hellowolrds** [comment]
会不会某个权限导致的呢
