### ISSUE TITLE
漫画图片问题

### ISSUE THREAD

**Issue by xianyvda** [Haleydu/Cimoc#20]
app颜色随系统   手机开了深色模式后漫画图片颜色会黑白反转  黑色变成白色 白色变成黑色  希望能解决

**Comment by Haleydu** [comment]
什么型号的手机？

**Comment by xianyvda** [comment]
小米9深色模式状态下    不开深色模式就没事

**Comment by Haleydu** [comment]
目前手上没有小米的手机，等我找个小米的手机，修复后验证一下

**Comment by zhongfly** [comment]
这显然和cimoc无关，应该是小米强制深色模式的问题，应该可以单独关闭某软件的深色模式。
解决办法可以参考 https://github.com/Kr328/ClashForAndroid/issues/558

你们小米用户都不清楚miui强制深色模式的原理吗？

**Comment by Haleydu** [comment]
小米手机的bug，无法解决
