### ISSUE TITLE
oppo手机一直报毒，什么时候能解决这个报毒问题！

### ISSUE THREAD

**Issue by feixuan520** [Haleydu/Cimoc#206]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [x] 搜索
- [x] 章节信息
- [x] 图片加载

## 你是否使用科学上网工具
- [x] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: oppo手机

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 1.6.31
每次打开手机都提示有恶意应用存在系统漏洞，请尽快清理，这个提示。请求能快点解决这个报系统漏洞的插件，谢谢！

**Comment by Haleydu** [comment]
报毒是某腾的杀毒引擎报毒，要给他们交钱才能解除。

**Comment by zhongfly** [comment]
如果你觉得app真的有病毒，可以卸载以避免中毒

**Comment by Haleydu** [comment]
新版本已解决报毒问题
