### ISSUE TITLE
可否增加无翻页动画模式

### ISSUE THREAD

**Issue by ChellyL** [Haleydu/Cimoc#209]
如题，目前应用的翻页方式为滑动，在墨水屏设备上使用时翻页会有很明显的拖影，非常辣眼睛，可否增加无翻页动画模式？

**Comment by Haleydu** [comment]
设置里有个快速翻页的功能，你试试看

**Comment by ChellyL** [comment]
在墨水屏设备上试了下，问题解决了，非常感谢！(๑•̀ㅂ•́)و✧
