### ISSUE TITLE
Release 版本号命名的建议

### ISSUE THREAD

**Issue by xz-dev** [Haleydu/Cimoc#21]
你好，我是 [UpgradeAll](https://github.com/DUpdateSystem/UpgradeAll) 的开发者。
根据用户反馈，我得知 Cimoc 项目被移交到你的手上，非常感谢你对于开源社区的贡献！
在粗略浏览项目后，我有以下建议：
1. 根据 [Github 官方文档](https://docs.github.com/en/github/administering-a-repository/about-releases) 与 [语义化版本号 2.0.0 文档](https://semver.org/lang/zh-CN/)
请尽量避免 1.5.6.1 这样的版本号出现
2. Release 标题一般与 Tag 相同
3. 版本号前面的 v 属于历史遗留写法（参考 [Is there a standard naming convention for git tags?](https://stackoverflow.com/a/6273142)），我想，你不会想念它的。

**Comment by Haleydu** [comment]
感谢你的建议

**Comment by saasddsaasdd** [comment]
请不要收录cimoc，有人拿他来卖钱，希望越少人知道越好

**Comment by xz-dev** [comment]
> 请不要收录cimoc，有人拿他来卖钱，希望越少人知道越好

使用**免费/开源软件**售卖，而获取不当利益的人当然可憎且违反协议。
作为个人开发者与 Cimoc 用户，我能够体会你希望保护软件的想法。

但是，我认为解决问题的方法不是去回避它，而是去正视去解决它
从用户的角度而言
1. 软件的用途就是去用，一般都不会去查看软件的关于页面，所以很有可能并不了解 Cimoc 是免费的，因而被“商家”坑害。
2. “商家”转售开源软件时，有一定概率修改/删除关于页面，以掩盖其行为。

从开发者的角度而言
1. 软件的持续开发建立于大量或是不断增长的用户数，无论它是否收费；收费可以带来利益，不收费可以带来名誉等等。因此，如果你希望软件能够长久存活，请让更多的人了解它，使用它。
2. 就防范“商家”转售行为，开发者可以通过软件内提示来告诉用户，这是免费软件，或者这是他人恶意分发给你的；当然，就我上面说的，商家可以去破解/修改这些信息。

因此，综上所述，解决这个问题，不能通过回避的方式；更不能说我不推广，没人用也就不会有人卖。
正如小米系统推出隐私防护功能，而最终的解决方案还是央视报导与工信部的制裁；这就是正视。
对于我们这些个人开发者或者开发团体，我们可以其揭露“商家”行为，可以去起诉商家，也可以加入用户提示。

但是，我认为，*成本最低且收益最高*的方法就是：让它足够出名，让大家都知道它是开源的，是不收费的。而这，也是“商家”们无法“破解”的，正如面对谣言的最好方法是让大家传播避谣信息。
（题外话：而 [UpgradeAll](https://github.com/DUpdateSystem/UpgradeAll) 或是其他应用市场的收录，就能够实现这个目标）

当然，如果 Cimoc 开发者要求不收录软件，我会取消收录。

**Comment by Haleydu** [comment]
感谢你的建议，版本号命名建议已采纳。
1.关于软件使用的问题，欢迎大家收录，欢迎大家使用。
2.关于软件被商家二次销售的问题，这个我无法控制，加入用户提示也是可以被修改，毕竟软件是开源的。还是需要大家去揭露“商家”行为，或者靠软件知名度去控制，我自己没有时间去运营推广这个软件，如果软件体验好的话，会用大量用户帮忙推广，用户的增长是建立在软件质量的基础上的。
