### ISSUE TITLE
[CS]能够增加CoCo漫画网的漫画源嘛

### ISSUE THREAD

**Issue by 18316059398** [Haleydu/Cimoc#215]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by zhongfly** [comment]
就是OH漫画

**Comment by 18316059398** [comment]
漫画台的搜索源坏了

**Comment by Haleydu** [comment]
Oh漫画就是，漫画台新版本已修复

**Comment by fengcd1234** [comment]
- 请问一下能不能用c#爬取coco漫画啊，我爬取不到这是报的错
![微信图片_20221010210450](https://user-images.githubusercontent.com/89008970/194873048-f05a18c1-dca5-4953-ae8e-8d5355c10f30.jpg)

**Comment by 1115501230** [comment]
已经收到您发送的材料，如果未备注清楚的文件，将不会被使用！若未备注清楚请备注好发过来。感谢您的阅读。
