### ISSUE TITLE
拷贝漫画已关闭h5版，APP端的接口可参照已有项目

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#220]
网站已关闭了H5版，只留下了app下载，其他项目实现了app端的漫画阅读，作者可以参考一下，节省时间 https://github.com/fumiama/copymanga

**Comment by finlong6424** [comment]
网页版好像又回来了，但是cimoc里图源是拷贝漫画的漫画依然是解析错误。
