### ISSUE TITLE
更新至安卓11后，Cimoc无法正常运行

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [Haleydu/Cimoc#227]
一加7PRO，贼后悔更新到安卓11

Cimoc打开后先白屏3-5分钟，之后显示主界面，打开一个漫画也需要3分钟。
这是系统的问题，还是APP需要优化一下呢？
求救。。

**Comment by ParanoiaIsGreat** [comment]
有什么log之类的东西我能提供吗？同样的手机同样的系统，别人正常使用，我就如上所说。。

**Comment by Haleydu** [comment]
备份一下自己收藏的漫画源，卸载重新安装一下。

**Comment by ParanoiaIsGreat** [comment]
> 备份一下自己收藏的漫画源，卸载重新安装一下。

试过了，还是一样

**Comment by Haleydu** [comment]
使用apk的时候有崩溃吗？没有崩溃或者闪退的问题，电脑用adb连接手机，用这条命令“adb shell logcat > oneplus.log ”，然后运行手机，复现问题后把这个oneplus.log文件发这里，我尽快修复

**Comment by ParanoiaIsGreat** [comment]
> 使用apk的时候有崩溃吗？没有崩溃或者闪退的问题，电脑用adb连接手机，用这条命令“adb shell logcat > oneplus.log ”，然后运行手机，复现问题后把这个oneplus.log文件发这里，我尽快修复

崩溃倒是没有，就是打开速度和打开某一漫画速度及慢，看漫画的加载速度还是正常的。我试试。

**Comment by ParanoiaIsGreat** [comment]
> 使用apk的时候有崩溃吗？没有崩溃或者闪退的问题，电脑用adb连接手机，用这条命令“adb shell logcat > oneplus.log ”，然后运行手机，复现问题后把这个oneplus.log文件发这里，我尽快修复

在什么时候运行命令？是要重启之后再运行命令，然后打开cimoc吗？以及这个log文件生成在哪？

**Comment by Haleydu** [comment]
我弄了个1.6.34-beta版本，你下载安装上去。正常使用软件就行了，运行一段时间软件，如果出现了你前面说的问题后。去手机的文件管理器有个cimoc文件夹 “/Cimoc/Log/crash”里面有个xcrash后缀的文件，发到这里就行了。

**Comment by Haleydu** [comment]
稍等一下就有了，刚上传代码，服务没那么快编译出来

**Comment by ParanoiaIsGreat** [comment]
> 稍等一下就有了，刚上传代码，服务没那么快编译出来

好的。。刚要问没apk。。

**Comment by ParanoiaIsGreat** [comment]
> 我弄了个1.6.34-beta版本，你下载安装上去。正常使用软件就行了，运行一段时间软件，如果出现了你前面说的问题后。去手机的文件管理器有个cimoc文件夹 “/Cimoc/Log/crash”里面有个xcrash后缀的文件，发到这里就行了。

没有生成文件。。还是说生成文件需要时间？

9.55分下载好安装完毕后打开app，10点整进入到主界面。
然后随意点了几个漫画，平均需要30多秒才能进入。
然后检查漫画更新途中闪退。
重新打开app又花了5分钟才进到主界面。
然后点了几个漫画后手动退出。

到现在为止只剩成了Crash文件夹，里面是空的。

**Comment by ParanoiaIsGreat** [comment]
xcrash是需要app崩溃或未响应才能生成吗？
上午除了“慢”以外正常使用，没有生成文件
刚才又试了试，打开漫画时出现了几次未响应的框框，最后一次时点了退出应用
然后去文件管理看到了生成的xcrash文件，如下：

[crash.zip](https://github.com/Haleydu/Cimoc/files/6371457/crash.zip)

**Comment by ParanoiaIsGreat** [comment]
今天突然恢复正常了。。是大佬修复了什么东西吗？就很奇怪。。

**Comment by Haleydu** [comment]
没有修复，看日志应该是你手机系统的问题的，估计是一加在后台升级系统的时候帮你把系统修复了吧
