### ISSUE TITLE
希望能增加阅读模式

### ISSUE THREAD

**Issue by h2822979** [Haleydu/Cimoc#235]
韩漫选手希望增加竖屏上滑模式！

**Comment by Haleydu** [comment]
可以去设置里面设置一下阅读模式

**Comment by h2822979** [comment]
设置过了，不过卷纸模式也是横向翻页

**Comment by Himmelt** [comment]
同求竖屏滚动

**Comment by Himmelt** [comment]
> 同求竖屏滚动
搞定了😂
![Screenshot_2021-06-09-13-28-27-574_com.haleydu.cimoc.jpg](https://user-images.githubusercontent.com/12007165/121298558-accd2d80-c926-11eb-93a8-9dc54bb17c46.jpg)

**Comment by Haleydu** [comment]
新版本增加了快捷切换阅读的模式
