### ISSUE TITLE
[CS]腾讯漫画源每次打开都是只有一张图片

### ISSUE THREAD

**Issue by Borzzj** [Haleydu/Cimoc#236]
具体版本：1.6.35
腾讯漫画源每次打开都是只有一张图片
使用的是华为P30pro手机

**Comment by keeno1982** [comment]
应该是付费的部分看不了，只有封面吧

**Comment by Haleydu** [comment]
不破解付费内容，可以用其他网站的漫画源替代，基本都可以找到

**Comment by q79701** [comment]
腾讯漫画的付费内容都只能显示第一页，后续的内容看不了，腾讯漫画源只不过是通过一些网页规则，把图片从腾讯漫画的网站收集在一起展示在你的看漫画APP上，并不是已经获取了漫画内，想看后面的还是要该付费的付费，该开会员的开会员，毕竟人家也是要吃饭的，不可能全部免费让你看吧！所以说遇到这种情况就换源就行了，一般其他的漫画源是通过在腾讯漫画开会员，把漫画内容下载了，再把图片上传到它的漫画搜集网站上的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月12日(周三) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Haleydu/Cimoc] [CS]腾讯漫画源每次打开都是只有一张图片 (#236)




 
Closed #236.
