### ISSUE TITLE
希望收藏的漫画增加一个《只显示更新的》功能

### ISSUE THREAD

**Issue by Borzzj** [Haleydu/Cimoc#237]
因为收藏了很多漫画，如果每个漫画都要点进去才能看到有没有更新会有些麻烦。
希望能增加一个只显示更新的漫画功能，或者把有更新的漫画放在第一个凸显出来也会更好使用！
谢谢！

**Comment by Haleydu** [comment]
收藏下面有个悬浮的刷新键，按一下就好了。或者去设置把自动检查更新打开
