### ISSUE TITLE
热辣漫画一些漫画每个章节里只有10页

### ISSUE THREAD

**Issue by UnuboreJoe** [Haleydu/Cimoc#239]
和之前拷贝漫画一样，热辣漫画一些漫画每个章节只有10页。

不过可以和拷贝漫画互补……不过都是10也的就倒霉了。

**Comment by zhongfly** [comment]
个人测试一切正常，你可以尝试直接在网页看，可能是网站自身问题
拷贝漫画和热辣其实是一样的图片数据

**Comment by Haleydu** [comment]
热辣的不再修复，它需要登录才能看全全部漫画
