### ISSUE TITLE
[CS]禁漫天堂

### ISSUE THREAD

**Issue by linkedcast** [Haleydu/Cimoc#242]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
禁漫天堂
## 您搜索/观看的漫画名称或关键字以及访问链接
所有的
## 在以下环节中出现错误
- [ ✓] 搜索
- [ ✓] 章节信息
- [ ✓] 图片加载

## 你是否使用科学上网工具
- [ ✓] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [✓ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [✓ ] 国产(小米/氢氧/锤子)
具体版本: PBBM30

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 1.6.3

**Comment by w1329414319** [comment]
禁漫天堂 凉了

**Comment by Haleydu** [comment]
科学上网还是可以正常看到

**Comment by tggddtujk** [comment]
禁漫天堂 凉了

**Comment by 1115501230** [comment]
已经收到您发送的材料，如果未备注清楚的文件，将不会被使用！若未备注清楚请备注好发过来。感谢您的阅读。
