### ISSUE TITLE
AndroidStudio 编译失败

### ISSUE THREAD

**Issue by MrRongs** [Haleydu/Cimoc#249]
第一个：
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'E:\testdemonew\Cimoc-release-tci\app\build.gradle' line: 19

第二个：
2: Task failed with an exception.
-----------
* Where:
Settings file 'E:\testdemonew\Cimoc-release-tci\settings.gradle' line: 41

* What went wrong:
Ambiguous method overloading for method java.lang.Long#minus.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.Character]
	[class java.lang.Number]

**Comment by Haleydu** [comment]
看看是不是自己编译环境的问题。项目都是自动编译的，release有生成apk代表着没有编译问题
