### ISSUE TITLE
功能建议: webdav同步进度或配置文件功能

### ISSUE THREAD

**Issue by kjlawrencelaw** [Haleydu/Cimoc#254]
如题，希望能在已有的备份功能上，添加定时或手动同步到webdav的功能，房间跨设备继续阅读

**Comment by schyjxy** [comment]
比如备份到坚果云？

**Comment by kjlawrencelaw** [comment]
> 比如备份到坚果云？

是的 或是更进一步可以跟legado的阅读似的 添加拉取云端进度 方便不同设备之间无缝观看

毕竟非专业人士也不知道这需求实现起来的难度 如果工作量太大 则能够webdav备份我就心满意足了

**Comment by schyjxy** [comment]
有现成的库，实现起来应该难度不大

**Comment by kjlawrencelaw** [comment]
可以实现功能又不会让dev太累 那这样皆大欢喜就太好了
我只能帮忙摇旗呐喊啊
\加油/

**Comment by Haleydu** [comment]
可以，争取今年上坚果云备份功能

**Comment by kjlawrencelaw** [comment]
那太棒了 提前感谢哇

最近常换设备阅读
早上用平板
晚上用eink
外出用手机

所以一直有进度方面的问题😶
好长一段时间都得靠记的

**Comment by Haleydu** [comment]
肝了一天，webdav搞定了
