### ISSUE TITLE
[CS]新版1.71安装不了，-103报错

### ISSUE THREAD

**Issue by 2987643340** [Haleydu/Cimoc#260]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by Haleydu** [comment]
我很好奇为什么你们下载之后软件明明只有5.1m的就变成了5.4m，是不是手机厂商做了处理?

**Comment by 2987643340** [comment]
我也不知道啊，现在只能用1.6.40看

**Comment by Haleydu** [comment]
GitHub的release已经修复了不能安装的问题，腾讯加固导致，做了一下优化。重新下载一下就好了
