### ISSUE TITLE
新版1.7.1 apk无法安装

### ISSUE THREAD

**Issue by Jason-2048** [Haleydu/Cimoc#261]
Cimoc 1.7.1 无法安装
一加8T 安卓11 氢os11.0.8.17.KB05
![image](https://user-images.githubusercontent.com/43310039/127422442-6b911e1b-8593-431e-a2d1-504ae1c92277.png)

**Comment by Haleydu** [comment]
我很好奇为什么你们下载之后软件明明只有5.1m的就变成了5.4m，是不是手机厂商做了处理?还是说只有特定手机才会这样

**Comment by ChellyL** [comment]
巧了我也是，一加手机，1dm从GitHub下载5.17m，一样无法安装……

**Comment by Jason-2048** [comment]
> 我很好奇为什么你们下载之后软件明明只有5.1m的就变成了5.4m，是不是手机厂商做了处理?还是说只有特定手机才会这样

文件管理器里是5.17m，打开“软件包安装程序”内就变成5.4m

**Comment by ChellyL** [comment]
> 
> 
> > 我很好奇为什么你们下载之后软件明明只有5.1m的就变成了5.4m，是不是手机厂商做了处理?还是说只有特定手机才会这样
> 
> 文件管理器里是5.17m，打开“软件包安装程序”内就变成5.4m

找到解决办法了，你去公众号，下载公众号提供的版本，4.7m那个，亲测可以安装，激活图源也要用gitee那个

**Comment by Haleydu** [comment]
GitHub的release已经修复了不能安装的问题，腾讯加固导致，做了一下优化。
