### ISSUE TITLE
已经授权SD卡文件访问权限，为何要所有文件的访问权限？

### ISSUE THREAD

**Issue by monklamn-zz** [Haleydu/Cimoc#263]
机型：红米K30Pro，Android11，miui12.5.2
问题：
已授权SD卡文件的访问权限，但是启动后依然要获取所有文件的访问权限。可否优化一下？谢谢
![1b7dc4f3c2b46a0ee373a766e6c1341](https://user-images.githubusercontent.com/31619993/127591539-b87507e0-33dc-4141-ba1e-fa9c180395eb.jpg)
![ef9a1fe8bf31d8595d53c5a236081e8](https://user-images.githubusercontent.com/31619993/127591549-39dffb81-b1d2-451e-8cdf-e42c430f5916.jpg)
![0d93c0417c6953c72a8d0cbddba3edc](https://user-images.githubusercontent.com/31619993/127591554-8405c16e-b35e-43c1-ad15-b02f0413d0ef.jpg)

**Comment by Haleydu** [comment]
下载最新版本试试

**Comment by monklamn-zz** [comment]
> 下载最新版本试试

刚才在github上下载了1.7.3版本，安装后打开，还是有那个弹窗

**Comment by Haleydu** [comment]
新版本已修复
