### ISSUE TITLE
[CS]关于漫画源问题/建议添加功能

### ISSUE THREAD

**Issue by Zfeng-zhuang** [Haleydu/Cimoc#27]
# 这是一个漫画源问题

- 某些漫画在电脑端网站中能搜索出来，但在Cimoc中却无法搜索出来.
- 存在部分漫画在Cimoc中观看或下载出现解析错误的情况，导致无法阅读此页或下载错误.
- 存在部分漫画在Cimoc中无法显示封面的情况.

建议添加功能：
- 能否在已下载中添加排序功能，按照漫画源或按照作品名称排序，方便因下载时候某些作品续集的排列

## 出现错误的漫画源
漫画DB：
https://www.manhuadb.com/
漫画柜：
https://www.manhuagui.com/

## 您搜索/观看的漫画名称或关键字以及访问链接
- 灌篮高手/无法搜索：https://www.manhuadb.com/manhua/121
- I'S/无法搜索：https://www.manhuadb.com/manhua/434

- 漫画DB与漫画柜所有漫画解析错误

## 在以下环节中出现错误
- [√] 搜索
- [  ] 章节信息
- [√] 图片加载

## 你是否使用科学上网工具
- [√] 是
- [  ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [√] 是
- [  ] 否

## 您手机的系统版本
- [  ] 原生(AOSP/LL/RR/Mokee等)
- [√] 国产(小米/氢氧/锤子)
具体版本: 
MIUI 12 Global
EMUI 9.1 Global

## 您使用的cimoc版本
- [  ] v1.5.4
- [  ] v1.5.5
- [√] v1.5.6
- [  ] v1.5.7
具体版本:

**Comment by darriousliu** [comment]
这个之前写漫画DB的人没用心，没把漫画信息写全，所以搜一个出来就报错了

**Comment by Haleydu** [comment]
1.5.8版本
问题已修复
