### ISSUE TITLE
[CS]古风漫画源加载不出图像

### ISSUE THREAD

**Issue by ciecilia** [Haleydu/Cimoc#28]
# 这是一个漫画源问题
加载不出图像

## 出现错误的漫画源
古风漫画
## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ✓] 图片加载

## 你是否使用科学上网工具
- [ ✓] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ✓] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ✓] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [✓ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by Haleydu** [comment]
1.5.6版本的，古风我的大部分是可以的，具体是什么漫画无法加载？

**Comment by ciecilia** [comment]
不知道，点击进去一直就卡在那个加载中。
也有可能是与我的系统有关，我现在的手机是MIUI11

**Comment by ciecilia** [comment]
不知道，点点击进去就一直卡在那个漫画加载页面，试了多部漫画同样如此，也有可能是与我的手机系统有关，我现在的手机系统版本是MIUI11，Android 10

**Comment by Haleydu** [comment]
应该是被杀毒软件限制联网了，移出限制就好了

**Comment by ciecilia** [comment]
没有被限制联网，1.5.1版本还能加载出该漫画源的漫画

**Comment by Haleydu** [comment]
下载最新版本1.5.8试试看

**Comment by ciecilia** [comment]
试过了，还是不行。

**Comment by YellowOrangeHuang** [comment]
老兄，试下把代理关了，我这边没开代理就能加载出来，再不济你可以在阅读设置那里设置个快捷重新加载，多刷新几下。
我这边是米8，Miui12，安卓10，跟你差不多，可能的是你的代理不太行

**Comment by YellowOrange98** [comment]
我这边是米8，Miui12，安卓10，跟你差不多，可能的是你的代理不太行

**Comment by YellowOrangeHuang** [comment]
又或者，具体是看的哪本漫画，看看我这里能不能加载出来。
