### ISSUE TITLE
未继续开源将违反 GPL

### ISSUE THREAD

**Issue by Rongronggg9** [Haleydu/Cimoc#281]
本 repo 自 1.6.37 (b525004) 以来，未再有实质性更新，而 release 和微信公众号仍在继续发布二进制，同时没有附上其他明确的源代码分发渠道。由于本 repo 源于 [feilongfl/Cimoc](https://github.com/feilongfl/Cimoc)，而后者采用 [GPLv3](https://github.com/Haleydu/Cimoc/blob/release-tci/LICENSE.md) 许可证分发并一直延续至本 repo，闭源分发二进制将违反许可证。

另外留意到您在微信公众号上分发所谓的「非公开版本」，及向打赏额度较高的粉丝分发特别编译的版本，前述行为如未明确向被分发人附上源代码，同样是违反 GPL 的行为。

这意味着 README 中的以下描述不再具有或不再完整具有可信度：
```
所有release由travis-ci编译发布，如果在release界面某个版本没有apk，那么要么是正在编译，要么就是编译失败了 使用pre-release版本会在每次启动时显示检查更新提示。 安卓apk下载地址软件下载
全部代码我都自己分析了一遍没有后门，没有木马，没有病毒，代码是开源的大家也可以帮忙分析
代码是开源的，apk是travis自动编译发布的，不放心的可以自己编译apk安装
本软件开发，是为了码农之间的技术交流，以及解决软件测试过程中出现的各种bug，本软件的代码全部开源。
```

这同时意味着 README 中的以下条款成为讽刺条款：
```
请二次开发软件遵守软件许可证。
```

**Comment by Haleydu** [comment]
目前软件一直都是免费的，而且也没有收费，广告收入和打赏收入都是用于软件的维护，广告也是可以自由选择是否开启的。报毒问题非公开版已解决，非公开版本是经过了重构后的，只是界面的UI设计和名称沿用了本程序，目前报毒版本的软件还是开源的。你也可以下载报毒版本继续用。readme已修改。

**Comment by Rongronggg9** [comment]
> 目前软件一直都是免费的，而且也没有收费，广告收入和打赏收入都是用于软件的维护，广告也是可以自由选择是否开启的。

请注意，GPL 没有将盈利和公益放在对立面，使用自由软体盈利是被允许的，甚至就是预期用途之一，只是——仍然必须一同分发源代码。**没有必要试图混淆自由软体和免费软体，免费分发乃至广告可关闭，在任何程度上都不是您闭源的挡箭牌。自由软体的公益，就是无附加条件一同分发源代码，是否盈利并非其考量。**


> 非公开版本是经过了重构后的，只是界面的UI设计和名称沿用了本程序。

只要含有哪怕一小段受 GPL 保护的源代码，您就必须开源。这同时也包括本 repo 中由除您以外的其他人贡献的代码。如果您要闭源，请移除或以净室原则重写以下代码：
* 所有来自 [feilongfl/Cimoc](https://github.com/feilongfl/Cimoc) 的代码
  * 来自 [KeaMedes/Cimoc](https://github.com/KeaMedes/Cimoc) 的代码除外（由于未附许可证的源代码通常被认为是无权使用、修改乃至分享的，原作者有权利追究责任，只是事实上 permissive。因此，移除或以净室原则重写它们，是更好的选择）
* 在本 repo 诞生后，本 repo 中所有不是由您编写的代码

**一句话，在 [LICENSE](https://github.com/feilongfl/Cimoc/blob/release-tci/LICENSE.md) 创建以后的所有不来自于您的贡献**

当然，您也可以请求 @feilongfl 向您特别分发非 GPL 的分发，但：
* 如果未征得在 [LICENSE](https://github.com/feilongfl/Cimoc/blob/release-tci/LICENSE.md) 创建以后的其他贡献者的同意，需要移除或以净室原则重写来自他们的代码。
* 如果征得了所有其他贡献者的同意，那么可以不作任何修改就闭源。


> readme已修改。

> 由于本程序每次更新源码发布新版本就被淘宝和拼多多商家二次修改编译，售卖本软件，违背了软件免费的使用的原则

受 GPL 保护的软体，不以免费使用为原则，您唯一可以谴责的，就是网络商家未开源（而您也在做一样的行为）。因此，在自由软体的世界里，您和他们没有什么区别。

> 以及将售卖软件后的风险转移到了这里。

很显然，这些都是写开源软体之前应当了解的，而不是您闭源的藉口。退一万步讲，闭源就能遏止网络商家的破解和售卖行为吗？不过是门槛高一些罢了。

> 源码将不定期发布，发布的源码也是已过有效性的源码。

这是违反 GPL 的。您必须为每个二进制分发一同附带对应该二进制分发的源代码，且该源代码必须继续以 GPL 分发，如果不是一同分发（直接附上源代码，或在显眼的地方附上获取源代码的方式），或分发的源代码不能对应该二进制分发，或不以 GPL 分发，即违反 GPL。
很显然，这也是您决定接手这个 GPL 软体之前应当了解的。GitHub 给 license 的图标是一个天平，想想为什么？

### GPL 是一个利用版权法维持软体自由的许可证。您的闭源行为是违反版权法的，在 [LICENSE](https://github.com/feilongfl/Cimoc/blob/release-tci/LICENSE.md) 创建以后的所有贡献者都有权起诉您。当然，这在违法成本极低的国家几乎是不可能发生的。您可以尽情地闭源，只要您觉得您还对得起在 [LICENSE](https://github.com/feilongfl/Cimoc/blob/release-tci/LICENSE.md) 创建以后的所有贡献者，只要您觉得您还对得起曾写在 README 里的`请二次开发软件遵守软件许可证`，只要您愿意把自己在自由软体世界里的身段降低到与非法售卖（注意：非法的行为不是售卖，而是不分发源代码）本软体的网络商家一样，就不会有任何可见的损失。我理解开发软体的不易，但这是 GPL，是自由软体，是 [Copyleft](https://zh.wikipedia.org/zh-cn/Copyleft) 软体，向 Copyleft 软体贡献代码，本身已经代表了对 Copyleft 的认同，而不是背弃。

**Comment by Haleydu** [comment]
是的，非公开版本全部代码都是重写之后的，每个文件都是

**Comment by Rongronggg9** [comment]
侵权的最小单位不是文件。私心上本人不太认为未经净室原则的重写后闭源一定能不违反 GPL。但既然您这么说了，顺颂时祺。
