### ISSUE TITLE
[CS]按导入图源没用咋回事

### ISSUE THREAD

**Issue by ccx123123** [Haleydu/Cimoc#282]
# 这是一个漫画源问题 n n> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复 n> 请您在提交本问题前仔细完成下面问题以便更好地解决问题. n> 如果有多个漫画源出错，请不要合并在一起，谢谢 n n## 出现错误的漫画源 n n## 您搜索/观看的漫画名称或关键字以及访问链接 n n## 在以下环节中出现错误 n- [ ] 搜索 n- [ ] 章节信息 n- [ ] 图片加载 n n## 你是否使用科学上网工具 n- [ ] 是 n- [ ] 否 n n## 你是否能够访问漫画源网页并成功加载漫画图片 n- [ ] 是 n- [ ] 否 n n## 您手机的系统版本 n- [ ] 原生(AOSP/LL/RR/Mokee等) n- [ ] 国产(小米/氢氧/锤子) n具体版本:  n n## 您使用的cimoc版本 n- [ ] v1.5.4 n- [ ] v1.5.5 n- [ ] v1.5.6 n- [ ] v1.5.7 n具体版本:

**Comment by Haleydu** [comment]
导入成功了不需要再次倒入
