### ISSUE TITLE
[CS]忆漫画-漫画源问题

### ISSUE THREAD

**Issue by jdxl11** [Haleydu/Cimoc#285]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
忆漫画-m.yimmh.com
## 您搜索/观看的漫画名称或关键字以及访问链接
每章节图片数超过50的所有漫画（条漫，单行本等）
示例：http://m.yimmh.com/chapter/2525063
           http://m.yimmh.com/chapter/2525063?page=2
           http://m.yimmh.com/chapter/2525063?page=3
这是同一章节，添加后续的语法应该不难。
## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [\/] 图片加载

## 你是否使用科学上网工具
- [\/] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [\/] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [\/] 国产(小米/氢氧/锤子)
具体版本: 华为P40（由于源网站禁止华为浏览器（自动屏蔽广告）于是用的米侠浏览器）

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 1.7.13（970）

跟上面漫画链接写的一样，这个漫画源每50张图片分到下一页，有130多张的就会分为3页，而现在cimoc只能读取第一页(也就是前50张图片）导致图片缺失，望修复，感激不尽。

**Comment by Haleydu** [comment]
公众号后台回复最新获取，已修

**Comment by jdxl11** [comment]
> 公众号后台回复最新获取，已修

经测试前50张图片（第一页）会重复一次（就是前50页又加载了一次，在第51张图片前有100张图片了），虽不影响整体阅读，但请在有空的时候加以修复，感谢。

**Comment by Haleydu** [comment]
1.7.14版本以修复
