### ISSUE TITLE
更新无法在旧版更新新版

### ISSUE THREAD

**Issue by 15061799376** [Haleydu/Cimoc#29]
就是在更新的时候，会冒出旧版和新版两个软件，无法在旧版这一层更新新版！！！

**Comment by YellowOrangeHuang** [comment]
换包名了，老兄

**Comment by Haleydu** [comment]
cimoc有很多版本，为区分不同版本，换了包名，会与原应用共存，不需要旧的版本，把就版本删除了就行了
