### ISSUE TITLE
忆漫画的现在看不见了，都是显示解析错误

### ISSUE THREAD

**Issue by taffyvicki** [Haleydu/Cimoc#294]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by jdxl11** [comment]
我也遇到了这个问题，这个原因是网站受到攻击（应该跟咱们cimoc用户没关系）开启了IP校检，需要输入验证码以证明不是攻击网站的机器人，但也就是代表只要输入验证码就开放了ip。手机进入m.yimmh.com，输入验证码后IP开放，就可以用cimoc看了。顺便问一下cimoc不会造成反复刷新的效果吧？被封IP就很尴尬了。@ Haleydu

**Comment by Haleydu** [comment]
> 我也遇到了这个问题，这个原因是网站受到攻击（应该跟咱们cimoc用户没关系）开启了IP校检，需要输入验证码以证明不是攻击网站的机器人，但也就是代表只要输入验证码就开放了ip。手机进入m.yimmh.com，输入验证码后IP开放，就可以用cimoc看了。顺便问一下cimoc不会造成反复刷新的效果吧？被封IP就很尴尬了。@ Haleydu

不会反复刷新，失败后不会再解析
