### ISSUE TITLE
[CS]作者是否对GPL3.0开源许可证有误解？

### ISSUE THREAD

**Issue by miewe** [Haleydu/Cimoc#298]
https://github.com/Haleydu/Cimoc/issues/281
@Rongronggg9 已经解释的很清楚了，关于readme里面的

> 关于淘宝售卖和会员破解
本程序没有任何破解网站VIP的功能，仅仅作为网页浏览器显示网站免费浏览部分，淘宝卖家自行添加的破解或其他功能与本程序无任何关系。
由于本程序每次更新源码发布新版本就被淘宝和拼多多商家二次修改编译，售卖本软件，违背了软件免费的使用的原则，以及将售卖软件后的风险转移到了这里。源码将不定期发布，发布的源码也是已过有效性的源码。

请举出实际修改或者售卖的例子，而不是含糊其辞模糊源代码实际发布时间。退一万步讲，假设淘宝卖家自行添加收费功能，请问这是否与GPL_v3.0许可证有何冲突？

> GPLv3在2007年发布，**它允许个人使用、商业使用**、专利授权，允许复制、分发、修改，**并且作者不承担用户使用的一切后果**。

既然在法律上已经明确不会由作者承担用户使用的一切后果，为何该作者Haleydu仍然要求闭源？除了**担心作者自己的实际收益会受到影响**外（植入广告等，当然，并不是反对这种行为，GPL3.0使用自由软体盈利是被允许的，甚至就是预期用途之一，只是——**仍然必须一同分发源代码**），已经想不到别的解释了。

顺便[tachiyomi](https://github.com/tachiyomiorg/tachiyomi/blob/master/LICENSE)使用的是Apache License 2.0。作者“如果”使用或“参考”了该项目的漫画源的代码的话，不该使用

> 设计思路
软件的设计思路来自国外知名的漫画软件“趣立”

**趣立** 这种似是而非的自造词来代替模糊真实来源吧？

**人往利趋，这没什么好说的，GPL3.0本身也没有把盈利和公益放在对立面。但请不要用所谓的开源许可来当挡箭牌。开发软体的不易，但这是 GPL，是自由软体，是 Copyleft 软体，向 Copyleft 软体贡献代码，本身已经代表了对 Copyleft 的认同，而不是背弃。**

**Comment by Haleydu** [comment]
关于广告的声明，软件内的广告几周前已经全部取消了。关于源码的声明：源码是会开放的出来的，原本的计划是每年年底将全部源码公开出来的。请问那么着急要源码是想要进行二次开发吗？

**Comment by Rongronggg9** [comment]
> 请问那么着急要源码是想要进行二次开发吗？
诉诸动机非常熟练。是谁拿了别人 GPL 的源代码二次开发然后闭源？

根据 GPL，您无权延迟发布源代码，源代码必须与二进制一同分发且必须能够编译得到相同的结果。延迟发布源代码与不发布源代码并没有什么不同，都是闭源行为。
GPL 的信奉者们可以不需理由要求分发代码，而 GPL 的背弃者们则只能靠诉诸 GPL 的信奉者们的动机来开脱。

**Comment by Haleydu** [comment]
用kotlin重构后的代码，如果你要扣细节的话，你可以找到一堆相似的逻辑。fresco/okhttp/rxjava/Greendao使用技术都是一样。为了解决原来的代码报毒问题，跟之前一样我能承诺的是每个代码文件全都是重写后的，不会有一样的代码。GPL也没有规定不能延迟公开源码，不知道你们如此着急获取源码有何意图。这个项目我都开源这么久了，也不怕你的质疑。想要最新代码二次开发后卖钱的可以直接私信我拿源码，没必要开个小号在这里质疑。关于说举售售卖例子的，我没有义务列举出来，只要你有心去搜索的都能搜到。

**Comment by Rongronggg9** [comment]
> GPL也没有规定不能延迟公开源码

您很喜欢玩文字游戏的话，我也可以陪你玩喔？
GPL 的确没有明文「规定不能延迟」，它规定的是「分发二进制的前提是同时分发机器可读的对应源代码」(You may convey a covered work in object code...provided that you also convey the machine-readable Corresponding Source...)。

> 6. Conveying Non-Source Forms.
>
> You may convey a covered work in object code form under the terms of sections 4 and 5, **provided that you also convey the machine-readable Corresponding Source under the terms of this License**, in one of these ways:
>
>    a) Convey the object code **in, or embodied in,** a **physical** product (including a physical distribution medium), accompanied by the Corresponding Source fixed on a durable physical medium customarily used for software interchange.
    b) Convey the object code **in, or embodied in,** a **physical** product (including a physical distribution medium), accompanied by a written offer, valid for at least three years and valid for as long as you offer spare parts or customer support for that product model, to give anyone who possesses the object code **either (1) a copy of the Corresponding Source for all the software in the product that is covered by this License, on a durable physical medium customarily used for software interchange, for a price no more than your reasonable cost of physically performing this conveying of source, or (2) access to copy the Corresponding Source from a network server at no charge.**
    c) Convey individual copies of the object code with a copy of the written offer to provide the Corresponding Source. This alternative is allowed **only occasionally and noncommercially**, and **only if you received the object code with such an offer, in accord with subsection 6b.**
    d) Convey the object code by offering access from a designated place (gratis or for a charge), and **offer equivalent access to the Corresponding Source in the same way through the same place at no further charge.** You need not require recipients to copy the Corresponding Source along with the object code. If the place to copy the object code is a network server, the Corresponding Source may be on a different server (operated by you or a third party) that supports equivalent copying facilities, **provided you maintain clear directions next to the object code saying where to find the Corresponding Source.** Regardless of what server hosts the Corresponding Source, **you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.**
    e) Convey the object code using peer-to-peer transmission, **provided you inform other peers where the object code and Corresponding Source of the work are being offered to the general public at no charge under subsection 6d.**

因您不是通过物理媒介分发二进制，`a)`, `b)`, `c)` 不适用于您；因您也不是向个人点对点分发二进制，而是向公众公开分发，`e)` 也不适用于您。
那么我们考虑 `d)` ,`d)` 适用的其中一种情况恰是以互联网为媒介分发二进制，它明确提到 `Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.`，翻译过来就是 `无论以什么样的服务器存放对应的源代码，您都有义务保证源代码在任何被需求的时候都（在服务器上）保持可用，才能满足上述要求`，您对 `任何被需求的时候` 的理解难道就是 `想要最新代码二次开发后卖钱`？不得不说您可真是心胸宽广。很遗憾，`任何被需求的时候` 是不需要附带理由的。由于在 `任何被需求的时候` ，您的分发所对应的源代码未能 `（在服务器上）保持可用` ，进而将不能 `satisfy these requirements`: ` Convey the object code by offering access from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge...If the place to copy the object code is a network server, the Corresponding Source may be on a different server (operated by you or a third party) that supports equivalent copying facilities, provided you maintain clear directions next to the object code saying where to find the Corresponding Source. `，基于此，您违反 GPL 的行为是无可抵赖的。
综上，逻辑严密的人不难推导出结论：通过互联网公开分发二进制时，延迟开源将与 ` Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.` 产生根本性抵触，您没能完成保证源代码在服务器上保持可用的义务（事实上，您没有按时分发源代码，源代码在服务器上从未可用过，这是仅次于永不分发源代码的最恶劣情况）。


> 可以直接私信我拿源码
无法帮助您逃脱 GPL 的魔爪，除非您以后所有二进制都是私信分发的。回去再读一遍上一段吧。


> 不知道你们如此着急获取源码有何意图
想要最新代码二次开发后卖钱的可以直接私信我拿源码
没必要开个小号在这里质疑

[诉诸动机](https://zh.wikipedia.org/wiki/%E8%A8%B4%E8%AB%B8%E5%8B%95%E6%A9%9F)是典型的[非形式谬误](https://zh.wikipedia.org/wiki/%E9%9D%9E%E5%BD%A2%E5%BC%8F%E8%AC%AC%E8%AA%A4)您知不知道呀？
实在说不了什么理，就只好拿「小号」、「卖钱」来呛人了。GPL 的目标可是 `to make sure it remains free software for all its users`，原来 `to make sure it remains free software for all its users == 二次开发后卖钱`。别人开一千个小号都有充分的质疑你的资格，更有着获取源代码的权利（但这权利被你以违反许可证的方式剥夺了）；而违反 GPL 的人，倒切切实实地有获得 GPL 第 8 条的资格了，哦，不是有资格，是自动获得。
自由软体人才不在意你的源代码长啥样、能不能拿来赚钱，甚至也不在意你的源代码有没有混淆得人类不可读。他们只在意你有没有按时分发源代码、分发方式是否合理、分发的源代码是否能与二进制对应，可比你这揣摩来揣摩去的心理单纯多了。你要没完成这义务，那他们可看不起这代码。我要是也有小号，也肯定不屑于浪费一个账号来理论的。


> 用kotlin重构后的代码，如果你要扣细节的话，你可以找到一堆相似的逻辑。fresco/okhttp/rxjava/Greendao使用技术都是一样。

您知不知道「重构」的代码在法律上是几乎没有不被认为雷同的余地的呀？很遗憾，GPL 就是利用合同和版权法来惩罚破坏软体自由的人的。你当然可以认为你就是失足落入了 GPL 的魔爪，怎么写都会雷同，但很遗憾，这也是你自愿的。


> 跟之前一样我能承诺的是每个代码文件全都是重写后的，不会有一样的代码。

被判抄袭的作家也说自己的「大作」和别人的「劣作」没有一句话是一样的，查下来，还真是没有一句话是一样的。你要说法院判错了吗？

<detail>
句句不离拿去卖钱，你真当懂开源许可证的人都是傻子，放着 permissive 还不报毒的 Tachiyomi 不拿，来拿你的违反 GPL 的闭源不报毒版 Cimoc？人家 Apache License 2.0，拿去闭源赚钱既不用有法律包袱，又不用有道德包袱，二次开发改不会了去问社区都不会被人非形式谬误，但凡是个懂开源许可证的人都知道怎么选。
就是不知道拿 Cimoc 闭源，不管赚没赚钱的人，有没有法律包袱，有没有道德包袱。（不要误会，我不是针对谁，我是说，拿 GPL 去闭源的各位，都希望你们没有包袱）
</detail>
