### ISSUE TITLE
[CS]

### ISSUE THREAD

**Issue by blue999999** [Haleydu/Cimoc#30]
## 出现错误的漫画源
腾讯动漫
## 您搜索/观看的漫画名称或关键字以及访问链接
任意，比如柯南
## 在以下环节中出现错误
- [x] 章节信息

## 你是否使用科学上网工具
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是

## 您手机的系统版本
具体版本: OneUI 2.1(Android 10)

## 您使用的cimoc版本
- [ ] v1.5.7
具体版本: 最近几个版本都存在腾讯动漫读取不到章节的问题，而飞龙大大的1.5.1正常。

**Comment by Haleydu** [comment]
腾讯的漫画源不打算优化，至于为什么，你懂得
