### ISSUE TITLE
主界面旋转屏幕BUG

### ISSUE THREAD

**Issue by KeyTeams** [Haleydu/Cimoc#39]
主界面检查更新时，如果旋转屏幕那么检查会断掉，有点像是程序崩溃过一遍一样，而且感觉这个旋转好多问题，躺在床上看漫画经常旋屏，旋屏又会崩溃，跟随手机旋转加个按钮开关或者去掉吧。还有看漫画时音量键控制漫画翻页也加个开关吧，不然边看漫画边听音乐要退出去才能调。

**Comment by Haleydu** [comment]
1.6.3版本已修复该问题
