### ISSUE TITLE
[CS]MangaBZ只能挂VPN看，望修复

### ISSUE THREAD

**Issue by mmsqzz** [Haleydu/Cimoc#43]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本:

**Comment by YellowOrangeHuang** [comment]
没有吧，是用的繁体关键字搜索的吗？

**Comment by mmsqzz** [comment]
> 没有吧，是用的繁体关键字搜索的吗？

繁体和简体都试过了，只能挂VPN

**Comment by YellowOrangeHuang** [comment]
那你最好多提供点信息，比如什么手机，什么系统，什么时候搜的什么漫画，现在搜可以搜到吗。
我现在是可以不用代理就搜MangaBz的。

**Comment by mmsqzz** [comment]
> 那你最好多提供点信息，比如什么手机，什么系统，什么时候搜的什么漫画，现在搜可以搜到吗。
> 我现在是可以不用代理就搜MangaBz的。

啊，抱歉，表达错误了，我的意思是里面的漫画得挂VPN才能看。

**Comment by YellowOrangeHuang** [comment]
是这种情况吗？
![photo_2020-08-03_13-02-30](https://user-images.githubusercontent.com/46016407/89147680-f3752d00-d589-11ea-9e5b-ecde2504ed9c.jpg)
如果是，重新加载一次就好了，在自定义点击事件那里设置一个重新加载图片
![photo_2020-08-03_13-04-13](https://user-images.githubusercontent.com/46016407/89147814-68486700-d58a-11ea-825e-0fab1dec9a78.jpg)

**Comment by mmsqzz** [comment]
> 是这种情况吗？
> ![photo_2020-08-03_13-02-30](https://user-images.githubusercontent.com/46016407/89147680-f3752d00-d589-11ea-9e5b-ecde2504ed9c.jpg)
> 如果是，重新加载一次就好了，在自定义点击事件那里设置一个重新加载图片
> ![photo_2020-08-03_13-04-13](https://user-images.githubusercontent.com/46016407/89147814-68486700-d58a-11ea-825e-0fab1dec9a78.jpg)

![Screenshot_20200803_131252](https://user-images.githubusercontent.com/68606457/89148029-25d35a00-d58b-11ea-977c-a3fab77c9e44.jpg)
这种情况

**Comment by YellowOrangeHuang** [comment]
@mmsqzz  是什么漫画，会不会是源的问题

**Comment by mmsqzz** [comment]
> @mmsqzz 是什么漫画，会不会是源的问题

五等分的花嫁

**Comment by YellowOrangeHuang** [comment]
多刷新几次，试试网络好一点的地方，我这边是一点问题都没有(=・ω・=)

**Comment by mmsqzz** [comment]
> 多刷新几次，试试网络好一点的地方，我这边是一点问题都没有(=・ω・=)

好的
