### ISSUE TITLE
漫画话数的顺序有时会颠倒，希望修复。

### ISSUE THREAD

**Issue by ONE223** [Haleydu/Cimoc#45]
漫画的话数顺序有时候会抽风，导致阅读时本该载入下一话会载入成上一话。
版本：1.62

**Comment by Haleydu** [comment]
具体点有哪些漫源会这样？观看哪部漫画？问题不够详细无法深入测试

**Comment by ONE223** [comment]
目前遇到的有动漫之家这个源。

**Comment by david446747602** [comment]
拷贝漫画-更衣人偶坠入爱河，同样有这个问题
