### ISSUE TITLE
安卓Q存储权限已给予，但仍设置闪退，无法备份。

### ISSUE THREAD

**Issue by ONE223** [Haleydu/Cimoc#5]
系统：Q，存储权限已给与，设置选项闪退，备份功能提示操作失败。机型：pixel2。

**Comment by YellowOrangeHuang** [comment]
你试下应用信息里的安装应用未知来源，设置成允许，我的安卓10也是这个问题，设置好了就没事了。

**Comment by ONE223** [comment]
安装未知应用里没有cimoc，无从修改。

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Schwi-ExMachina** [comment]
现在的问题是配置文件读取和生成，而不是app再安装，只需要储存空间，和未知应用没关系啊。

**Comment by Haleydu** [comment]
已修复
