### ISSUE TITLE
[CS]咚漫的目录显示不完全

### ISSUE THREAD

**Issue by YellowOrangeHuang** [Haleydu/Cimoc#54]
漫画目录只显示可观看的最后10章，之前的章节无法显示

**Comment by YellowOrangeHuang** [comment]
另外，能否添上咚漫的MangaCategory？

**Comment by aa13423554693** [comment]
我也发现新添加的咚漫漫画源有问题，目录只显示后面的，前面的章节没有！

**Comment by Haleydu** [comment]
提供一下漫画名，还是说大部分都会这样？

**Comment by YellowOrangeHuang** [comment]
> 提供一下漫画名，还是说大部分都会这样？

都是这样的，全部的大于10章的漫画都是这个问题
![Screenshot_2020-08-10-11-57-34-529_com haleydu cimoc](https://user-images.githubusercontent.com/46016407/89750991-e5cb2480-db00-11ea-9b3f-c552fa349e5c.jpg)
![Screenshot_2020-08-10-11-58-04-731_com haleydu cimoc](https://user-images.githubusercontent.com/46016407/89750995-e82d7e80-db00-11ea-9766-0a16546cadbb.jpg)
