### ISSUE TITLE
[CS]漫画堆和咚漫的问题

### ISSUE THREAD

**Issue by YellowOrangeHuang** [Haleydu/Cimoc#59]
版本：1.6.4-beta02

漫画堆：今天早上漫画堆的源https://m.manhuabei.com/list/
502了，所以暂时没办法修复，但昨天又换了一遍密匙……

咚漫：图片浏览页面，下方的进度条和右上的图片进度显示存在bug，不会随图片下一张而变动，通过进度条跳转图片，app会强退。
(土豪漫画也有这个相同的问题)

**Comment by YellowOrangeHuang** [comment]
新情况，在我5分钟前浏览漫画堆网页时还是502，但现在源网站已经正常，app上也能正常浏览漫画🤧

**Comment by cyu000** [comment]
漫画堆换key换的太频繁了

**Comment by Haleydu** [comment]
1.6.4-beta02版本应该是正常的吧

**Comment by Haleydu** [comment]
进度条的bug会尽快修复
