### ISSUE TITLE
关于漫画堆key经常更换的技术性讨论

### ISSUE THREAD

**Issue by sdyby2006** [Haleydu/Cimoc#60]
有没有办法可以自动获取key？
想先确定一下是否存在可自动获取的情况，若有，有没有可能每次打开软件的时候自动获取一下，然后修改了就刷新到配置文件里面的对应行里面，界面提示更改了key文件进行重启配置这种操作？
若没有可以就没办法了估计_(:зゝ∠)_

**Comment by Haleydu** [comment]
漫画堆的js是加密，没办法自己获取，目前漫画堆的key都是自己去分析的，写个软件去分析的话工作量太大了，目前不打算做。

**Comment by zhongfly** [comment]
可以在github或其他地方放一个文本，每次启动去请求内容，免得每次都需要软件版本更新…

**Comment by sdyby2006** [comment]
Github偶尔性抽风，可以考虑码云其实，开个公共项目单独存，这样免得每次更新会比较麻烦，而且相对稳定？0w0

**Comment by darriousliu** [comment]
最新的来了
`key="1739ZAQ54321bbG1"
iv="ABCDEF1G344321bb"
`

**Comment by Haleydu** [comment]
漫画最新的4天前已经改好了，你们直接下载最新版本就行了
