### ISSUE TITLE
[CS]禁漫天堂的源失效，麻烦修复一下，谢谢

### ISSUE THREAD

**Issue by Zyb196455** [Haleydu/Cimoc#63]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [x] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 
1.6.4

**Comment by Haleydu** [comment]
请先按照格式填一下，我刚刚测了一下是正常的

**Comment by Zyb196455** [comment]
> 请先按照格式填一下，我刚刚测了一下是正常的

能搜索出来，但没有章节信息

**Comment by Zyb196455** [comment]
> # 这是一个漫画源问题
> > 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> > 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> > 如果有多个漫画源出错，请不要合并在一起，谢谢
> 
> ## 出现错误的漫画源
> ## 您搜索/观看的漫画名称或关键字以及访问链接
> ## 在以下环节中出现错误
> * [ ]  搜索
> * [x]  章节信息
> * [ ]  图片加载
> 
> ## 你是否使用科学上网工具
> * [x]  是
> * [ ]  否
> 
> ## 你是否能够访问漫画源网页并成功加载漫画图片
> * [x]  是
> * [ ]  否
> 
> ## 您手机的系统版本
> * [ ]  原生(AOSP/LL/RR/Mokee等)
> * [x]  国产(小米/氢氧/锤子)
>   具体版本:
> 
> ## 您使用的cimoc版本
> * [ ]  v1.5.4
> * [ ]  v1.5.5
> * [ ]  v1.5.6
> * [ ]  v1.5.7
>   具体版本:
>   1.6.4
