### ISSUE TITLE
服务器费众筹

### ISSUE THREAD

**Issue by ciecilia** [Haleydu/Cimoc#67]
作者打算添加服务器用来云解析漫画源的话，在添加谷歌广告系统同时可以添加维护服务器的众筹收款二维码

**Comment by shenmintao** [comment]
在github上放一个配置文件不就好了，启动app的时候读一下，为啥还要花钱买服务器。

**Comment by Haleydu** [comment]
感谢各位。目前不必众筹，不会公开自己收款码，最近几天自己公司项目比较忙，还没有那么快到服务器的开发，平时都是抽时间来更新这个项目的，比如周末时间。软件不以盈利为目的。不会收大家的钱，加入广告的话就不用大家破费了，广告的收入都会用到这款软件上，反正也不多维护个服务器应该是够的。广告不会放在漫画浏览页，会尽量设计的不影响大家使用，毕竟我也要用这款软件看漫画😂

**Comment by Haleydu** [comment]
> 在github上放一个配置文件不就好了，启动app的时候读一下，为啥还要花钱买服务器。

github会有部分人无法访问，打算用服务器是因为漫画源会经常解析失败，比如以前解析成功的资源可以利用起来，免得漫画源更新后以前解析成功的那部分漫画也没得看了。

**Comment by tellw** [comment]
作者接广告三思啊
https://adnmb.com/t/29418727

**Comment by zhongfly** [comment]
github访问的问题可以通过jsdeliver的免费cdn解决，jsDeliver是有中国大陆唯一有牌照的公有 CDN

> jsDelivr is the only public CDN with a valid ICP license issued by the Chinese government, and hundreds of locations directly in Mainland China.

使用方法：例如https://github.com/Haleydu/Cimoc/blob/release-tci/README.md (默认分支)，使用jsDeliver cdn的地址https://cdn.jsdelivr.net/gh/Haleydu/Cimoc/README.md

> > 在github上放一个配置文件不就好了，启动app的时候读一下，为啥还要花钱买服务器。
> 
> github会有部分人无法访问，打算用服务器是因为漫画源会经常解析失败，比如以前解析成功的资源可以利用起来，免得漫画源更新后以前解析成功的那部分漫画也没得看了。

**Comment by zhongfly** [comment]
还有个偏门的方法，用zeit.co来当服务器，直接import github项目，在不含有index.html时会把项目所有文件列出来( https://vercel.com/docs/directory-listing )，国内访问速度也还可以并且不被屏蔽，还可以再套上cf的cdn(可能反而减速)

**Comment by KoedaNagi** [comment]
加入广告收入，以后怕会出事
