### ISSUE TITLE
[CS]动漫之家v2章节列表显示不全 排列顺序不统一

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#69]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫之家v2
## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 
1.6.5

动漫之家v2源的所有漫画最多只显示12话，正好是网页端不展开章节列表时显示的范围。示例 http://m.dmzj.com/info/41028.html
章节顺序不统一，示例：[漫画1](http://m.dmzj.com/info/45497.html) 与[漫画2](http://m.dmzj.com/info/41028.html) 的章节排列顺序始终相反，导致即使使用“反转列表”功能后，依旧有漫画章节顺序错误。

**Comment by YellowOrangeHuang** [comment]
补充下，所有漫画都最多只能显示12章漫画
