### ISSUE TITLE
[CS]漫画堆解析错误

### ISSUE THREAD

**Issue by Remarkab** [Haleydu/Cimoc#7]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/2)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
V1.4.8.8xxx

**Comment by Schwi-ExMachina** [comment]
好像是链接里的dui变成bei了

如果以后能对漫画解析也能备份恢复，那就可以用户自己修复了

**Comment by Haleydu** [comment]
已修复

**Comment by ONE223** [comment]
> 已修复

好像有部分漫画还是载入不了，网站可以看。

**Comment by ONE223** [comment]
漫画堆源有部分漫画搜索不出来，网站有。

**Comment by Haleydu** [comment]
修复了大部分，可能还有小部分无法观看。下载最新版本测测看
