### ISSUE TITLE
oh漫画部分解析错误

### ISSUE THREAD

**Issue by shinozaki7** [Haleydu/Cimoc#79]
版本1.6.6 oh漫画部分解析错误 比如 迷宫饭，租借女友等

**Comment by Haleydu** [comment]
oh漫画这个网站有点东西，白天某些版权漫画无法搜索，晚上就正常了，或者挂个代理也正常了。刚刚去测了一下，这两个在挂代理的时候可以正常看。如果解析错误的话，可以先去网站上看看是否可以正常浏览。

**Comment by YellowOrange98** [comment]
这个漫画源跟大妈之家有点像，凌晨固定时间段内才能看某些漫画，或者你挂代理

**Comment by YellowOrangeHuang** [comment]
> oh漫画这个网站有点东西，白天某些版权漫画无法搜索，晚上就正常了，或者挂个代理也正常了。刚刚去测了一下，这两个在挂代理的时候可以正常看。如果解析错误的话，可以先去网站上看看是否可以正常浏览。

这里补充下情况，现在OH漫画的图片加载出现了解析错误，我用这个源看的有倚天屠龙记、笑傲江湖、神雕侠侣、寄生少女，这些是可以在正常时间段阅读的漫画。

**Comment by Haleydu** [comment]
oh又换加密算法了，刚刚简单分析了一下，换成了两套算法同时解析。有套算法已经分析出来，就是换了个秘钥。第二套算法是直接放图片url，感觉这套好一点，相对软件来说计算量少一点，等分析出来明天更新。
