### ISSUE TITLE
[CS]建议添加两个漫画源

### ISSUE THREAD

**Issue by strbug** [Haleydu/Cimoc#8]
拷贝漫画
https://www.copymanga.com/
这网站貌相接受用户投稿，所以有些它自家特有资源，漫画更新速度还可以。

oh漫画
https://www.ohmanhua.com/
别看这网站一堆国漫，其实是藏木于林，里面也有不少该网站特有资源，估计是真花钱自己扒的。

还有其实可以关闭下已经解决了的问题反馈

**Comment by Haleydu** [comment]
感谢你的建议，会尽量抽时间更新这两个漫画源的

**Comment by Haleydu** [comment]
oh漫画源已加，拷贝漫画等有空再加上

**Comment by Haleydu** [comment]
拷贝漫画和oh漫画已添加
