### ISSUE TITLE
[CS]oh漫画已经下载的无法阅读解析错误

### ISSUE THREAD

**Issue by wwf40ji3000** [Haleydu/Cimoc#82]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
oh漫画
## 在以下环节中出现错误
- [x] 图片加载

## 你是否使用科学上网工具
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 否

## 您手机的系统版本
小米mix2s miui12.0.1
具体版本: 
miui12.0.1

## 您使用的cimoc版本

具体版本: 
1.6.8(94)

**Comment by Haleydu** [comment]
可能需要重新下载了，代码做处理特殊符号的时候忘记跟老版本做兼容了。或者通过本地导入观看。不止oh漫画，应该很多漫画都会有问题。删除重新下载问题应该可以解决。

抱歉了大家，造成这种低级错误。

**Comment by Haleydu** [comment]
下载后的漫画应该会有部分出问题，在线观看的不会有问题。

**Comment by Haleydu** [comment]
因为我自己都是在线看的没有下载，所有下载部分没有测试。抱歉抱歉。
