### ISSUE TITLE
关于漫画源的改进意见，不知可否修改为插件模式？

### ISSUE THREAD

**Issue by ONE223** [Haleydu/Cimoc#83]
![Screenshot_20200823-073115](https://user-images.githubusercontent.com/68263164/90967544-400db180-e513-11ea-9803-0d06159346bc.png)

因为漫画源频繁失效等问题，每一次出现源的更新就需要对整个应用进行重新下载安装等，比较费时费力。因此希望可以将漫画源改进类似多多猫的插件模式，开发者可以直接通过更新插件，用户也可以在第一时间收到更新提醒。

**Comment by Haleydu** [comment]
正在考虑一种比插件更好的方案来更新，目前的软件框架改插件模式需要大改软件。而且插件还需要用户去检查更新和安装。跟我们目前整体的软件更新好像大同小异，就是比更新软件方便一点。以后的开发方向应该是软件在线更新漫源解析方式。
