### ISSUE TITLE
[CS]建议添加漫画源：热辣漫画

### ISSUE THREAD

**Issue by player0898** [Haleydu/Cimoc#84]
热辣漫画：mrhotmanga.com

应该是copy漫画的里站，一般向内容更新速度是同步的，加载速度感觉比copy漫画快一点，相比copy漫画多了一些付费后才能观看的h动漫的内容

**Comment by Haleydu** [comment]
热辣的不再修复，它需要登录才能看全全部漫画

**Comment by wuxbko** [comment]
希望添加一个热辣漫画的源
