### ISSUE TITLE
1.6.11版本漫画堆还是不加载啊

### ISSUE THREAD

**Issue by 2436819833** [Haleydu/Cimoc#89]
开不开vpn都加载不了，大佬建个QQ群吧，反馈问题更方便。部分像《电锯人》可以加载，但是《没有名字的怪物》和其他很多都加载不了

**Comment by Haleydu** [comment]
没有QQ，我过几天去申请一个吧，到时开个QQ群

**Comment by Haleydu** [comment]
想想QQ群还是太麻烦了，不搞QQ群了
