### ISSUE TITLE
[建议]为了版本共存，最好包名与原分支不同

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#9]
由于包名一样，安装此分支的apk会安装失败(由于版本号低？)，并且另一方面新的分支也不应该和原来是一样的包名。
建议使用新的包名

**Comment by Haleydu** [comment]
包名已修改，等下个版本

**Comment by Haleydu** [comment]
等加了别人推荐的oh漫画源后会发个新版本。
