### ISSUE TITLE
添加新的翻页方式

### ISSUE THREAD

**Issue by Lay233** [Haleydu/Cimoc#91]
请问能否让每页上下拼接到一起，直接屏幕下拉可以看到不同页？现在的手机尺寸都比较长，每页上下有非常多的黑边。如果可以像哔咔漫画一样滑动就好了。

**Comment by ciecilia** [comment]
可以设置的啊！你可以在那个阅读模式那里更改

**Comment by Lay233** [comment]
> 可以设置的啊!你可以在那个阅读模式那里更改

晚上再捣鼓时看见了，不好意思
