### ISSUE TITLE
[CS]部分漫画源快捷保存图片失败问题

### ISSUE THREAD

**Issue by YellowOrangeHuang** [Haleydu/Cimoc#92]
问题源：奇漫屋、漫画堆、漫画160、咚漫漫画、MangaBz、百年漫画、禁漫天堂、漫画love、动漫之家、还有两个外文网。
如果某一个漫画章节下载缓存好了，在这个章节下进行快捷图片保存，会保存失败。
当然我也不太确定是否只有这几个源，但最近几个版本有过更新的源都可以测试下，几个比较老的源漫画BD、动漫之家v2就不会有这个问题。
特别地，奇漫屋源不论章节是否下载好了，都会快捷图片保存失败。
版本：1.6.11

**Comment by YellowOrangeHuang** [comment]
PS.还有一个隐患，漫画堆经过多次更新修改，我之前很久前下载缓存好的几部漫画堆漫画在cimoc的下载界面观看也已经会解析失败。

**Comment by YellowOrangeHuang** [comment]
当然隐患这个目前不是大问题，已经缓存好的漫画在本地界面还是可以正常阅读，还可以重新缓存，重新缓存后的漫画可以正常观看。
快捷图片保存失败也基本上不会影响阅读体验。
但还是希望大佬可以考虑下这两个隐患。
大佬辛苦了。😘

**Comment by Haleydu** [comment]
我明天再看看，修复一下吧

**Comment by Haleydu** [comment]
我明天再看看，修复一下吧
