### ISSUE TITLE
[CS]动漫之家v2 章节显示不全

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Cimoc#93]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/Haleydu/Cimoc/projects/1)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫之家v2

## 您搜索/观看的漫画名称或关键字以及访问链接
http://m.dmzj.com/info/52364.html

## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
- [ ] v1.5.4
- [ ] v1.5.5
- [ ] v1.5.6
- [ ] v1.5.7
具体版本: 
1.6.11

## 问题描述
http://m.dmzj.com/info/52364.html
该漫画章节有2个系列，而cimoc只显示上方的那一系列章节，而不显示“其他系列”的章节

**Comment by Haleydu** [comment]
好的，明天再修复

**Comment by Haleydu** [comment]
其它系列有显示啊，只是显示的不明显。在最下面可以找到。

**Comment by zhongfly** [comment]
> 其它系列有显示啊，只是显示的不明显。在最下面可以找到。

我很确信我所使用的1.6.11版本没有。
如图：
![Screenshot_20200830-072827](https://user-images.githubusercontent.com/11155705/91647865-b457d000-ea92-11ea-8881-0e0273039b1c.jpg)
上下滑动也没有更多章节了

对比网页上：
![Screenshot_20200830072904](https://user-images.githubusercontent.com/11155705/91647872-d4878f00-ea92-11ea-94c1-f2bec7d3b698.png)

很明显cimoc缺少了连载的章节，从章节数量都能明显看出，名为“连载01”-“连载09”的章节是没在cimoc中显示的

漫画链接依旧是我给出的https://m.dmzj.com/info/52364.html

**Comment by Haleydu** [comment]
v2确实有问题，昨天测的动漫之家没问题就没看了。会尽快修复
