### ISSUE TITLE
恢复收藏失败

### ISSUE THREAD

**Issue by bliu2683** [Haleydu/Cimoc#96]
V1.6.12，收藏和历史记录无法读取

**Comment by 2436819833** [comment]
非但无法读取，搜索新漫画还会直接闪退

**Comment by machdive** [comment]
更新以后反复跳失败，还删干净了我存的漫画

**Comment by Haleydu** [comment]
该本版可能会有挺多bug，1.6.11漫源能用的先不用着急升级
因为将解析的数据保存到本地，使得解析成功的漫画不会再解析失败，原来的数据库无法做到。
改了原来的数据库，可能会出现漫画加载失败的问题、搜索闪退的问题，卸载重新安装即可解决
等这个版本反馈的问题解决后，会发个正式版本。

优化了很多功能，还没时间去测。新版本漫画加载速度会比原来快很多，解析过的漫画不会再解析失败。
昨天TravisCI自动编译完就发布出来，没改成预发布版本。

**Comment by Haleydu** [comment]
想体验新版本的，可以卸载原来的，重新安装，功能就全部正常了，卸载前记得备份。
