### ISSUE TITLE
更新后所有功能均无法使用

### ISSUE THREAD

**Issue by dangdangzi** [Haleydu/Cimoc#97]

**Comment by Haleydu** [comment]
该本版可能会有挺多bug，1.6.11漫源能用的先不用着急升级
因为将解析的数据保存到本地，使得解析成功的漫画不会再解析失败，原来的数据库无法做到。
改了原来的数据库，可能会出现漫画加载失败的问题、搜索闪退的问题，卸载重新安装即可解决，问题就可以解决了
等这个版本反馈的问题解决后，会发个正式版本。

**Comment by Haleydu** [comment]
如果不用卸载的方式可以去设置里面清除应用存储数据，重新在“备份”里面恢复一下漫画数据可以了

**Comment by dangdangzi** [comment]
感谢回复!静等新版本发布。
另外能否添加一个打赏渠道?如果投放广告担心法律问题的话，这样多少能慰藉作者的辛劳
