### ISSUE TITLE
新版本看漫画会闪退。

### ISSUE THREAD

**Issue by ffffscp** [Haleydu/Cimoc#98]

**Comment by Haleydu** [comment]
能给一下操作流程吗？

**Comment by Haleydu** [comment]
从哪个版本升级上来的？

**Comment by ffffscp** [comment]
就是在点开漫画浏览几页之后，就退回桌面了。卸载重新安装后也一样，不知道怎么回事。

**Comment by ffffscp** [comment]
是从1611升级的。

**Comment by Haleydu** [comment]
好的，感谢

**Comment by Haleydu** [comment]
浏览的什么漫画？哪个漫源的？加快bug修复

**Comment by ffffscp** [comment]
我又试了一下，漫画堆，土豪，古风，动漫屋好几个，都一样，感觉不是漫画源的问题。

**Comment by YellowOrangeHuang** [comment]
@Haleydu 在翻页模式下阅读， 如果频繁使用下方进度条进行页数比较大的跳转，就会出现强退；而卷纸模式下，则没有这种情况。

**Comment by ffffscp** [comment]
但我是一页一页的翻页的，不过我试了一下卷纸模式没有这种情况。

**Comment by Haleydu** [comment]
已修复，可以帮忙测测看1.6.14版本的还会不会

**Comment by ffffscp** [comment]
好的。

**Comment by ffffscp** [comment]
多谢作者，作者辛苦了。没有问题了。

**Comment by Haleydu** [comment]
好的感谢测试，新版有其它问题可以继续反馈

**Comment by Haleydu** [comment]
@YellowOrange98 已修复，可以试试看新版本

**Comment by YellowOrangeHuang** [comment]
@Haleydu  新版本的翻页模式不会有这种问题了，感谢大大 @
