### ISSUE TITLE
[CS]禁漫天堂部分漫画详情页解析失败

### ISSUE THREAD

**Issue by YellowOrangeHuang** [Haleydu/Cimoc#99]
可以正常搜索，但进入详情页后，部分漫画无法加载章节，一些韩漫倒是没有问题(如:H-mate)，而其他漫画则会解析错误(如搜索“翻译”显示的结果)。

版本：1.6.14-beta01

**Comment by YellowOrangeHuang** [comment]
能解析的都是有多章节的漫画，而只有单独一个章节的，则会解析错误。

**Comment by Haleydu** [comment]
好的
